### ISSUE TITLE
[Bug] Cant import Proxmox VMs NOR connect to VMs

### ISSUE THREAD

**Issue by vmhomelab** [gnmyt/Nexterm#77] opened 2024-09-05 18:10 UTC
### General

- [X] I have updated to the latest version of Nexterm.
- [X] My bug has not been reported yet.

### The Bug

I deployed the container.
Added 2FA.
Imported Proxmox Server. VMs not showing up?
Added Windows Server VMs. Cant connect. Connection screen opens and then closes instantly.
Tried it with a new deployment. Same error.

### What device are you using to access the page?

In the browser

### Which operating system is your Nexterm instance running on?

Linux

**Comment by samumatic** [comment] 2024-09-12 18:15
Possible duplicate of #76

**Comment by gnmyt** [comment] 2024-09-14 14:23
It seems to be the same problem as #76. I'll create a PR to fix this issue. If your issue still occurs in the next version (`1.0.2`), feel free to re-open this issue.

**Closed** 2024-09-14 14:29 UTC
Labels: bug
